### ISSUE TITLE
只有中文会报错

### ISSUE THREAD

**Issue by ShylilyC** [Noriverwater/flowernovelzhHans#3]
[traceback.txt](https://github.com/user-attachments/files/16324690/traceback.txt)

**Comment by codeforker654** [comment]
请用[最新（三周年）版本的补丁](https://github.com/Noriverwater/flowernovelzhHans/releases/tag/reboot)，或许你安装了旧版本的补丁？记得把旧补丁删掉。

**Comment by ShylilyC** [comment]
> 请用[最新（三周年）版本的补丁](https://github.com/Noriverwater/flowernovelzhHans/releases/tag/reboot)，或许你安装了旧版本的补丁？记得把旧补丁删掉。

谢谢大佬，搞好了
![7kybkauq8U](https://github.com/user-attachments/assets/0db666db-b0ff-44f4-a8e3-51b3217f3e58)
